name: riseup-stayhigh  # for serving static files

networks:
  proxy:
    external: true

services:
  web:
    image: nginx
    volumes:
     - ./html:/usr/share/nginx/html:ro
     - ./server.conf:/etc/nginx/conf.d/server.conf
    environment:
     - NGINX_HOST=riseup-asso.fr
    labels:
      traefik.http.routers.riseup-stayhigh-web.entrypoints: websecure
      traefik.http.routers.riseup-stayhigh-web.rule: Host(`riseup-asso.fr`)
      traefik.http.services.riseup-stayhigh-web.loadbalancer.server.port: 80
      traefik.enable: true
    networks:
      - proxy

